version: '3.7'
services:
  spring-authorization-test-server:
    build:
      context: spring-authorization-test-server\
      dockerfile: Dockerfile
    image: spring-authorization-test-server:latest
    expose:
      - 8080
    ports:
      - 8090:8080
  resource-test-server:
    build:
      context: resource-test-server
      dockerfile: Dockerfile
    image: resource-test-server:latest
    expose:
      - 8080
      - 5005
    ports:
      - 8091:8080
      - 5005:5005
  client-to-resource-server:
    build:
      context: client-to-resource-server
      dockerfile: Dockerfile
    image: client-to-resource-server:latest
    expose:
      - 8080
      - 5006
    ports:
      - 8080:8080
      - 5006:5006